#!/bin/bash

error='\e[1;41m' # Red with white background
info='\e[0;93m' # yellow

echo -e "${info}Updating dependencies...${NC}"
npm i

echo -e "${info}Building app...${NC}"
npm run build

